version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    networks:
      - voice_ordering_network
    restart: unless-stopped

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  voice_ordering_network:
    name: voice_ordering_network
    driver: bridge